### ISSUE TITLE
version solving failed 

### ISSUE THREAD

**Issue by tony123S** [espresso3389/flutter_pdf_render#22]
How to fix?

    The current Flutter SDK version is 1.5.4-hotfix.2.   
    
    Because pdf_render 0.64.1 requires Flutter SDK version >=1.10.0 <2.0.0 and no versions of pdf_render match >0.64.1 <0.65.0, pdf_render ^0.64.1 is forbidden.
    So, because abc depends on pdf_render ^0.64.1, version solving failed.
    
    pub get failed (1)
    exit code 1

**pubspec.yaml**

    version: 1.0.0+1
    
    environment:
      sdk: ">=2.2.2 <3.0.0"
    ....

**Comment by espresso3389** [comment]
Sorry, I just released a patched release 0.66.1 that fixes the sdk version constraints.

```yaml
environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"
```
