### ISSUE TITLE
On iOS rendering of vectoriel pdf est lighter than expected.

### ISSUE THREAD

**Issue by JeanChristopheMobizel** [espresso3389/flutter_pdf_render#29]
`PdfViewer( filePath: widget.filePath,)`

On iOS device rendering of vector pdf are lighter than expected (in comparison with Google Drive or native file preview)

![pdf](https://user-images.githubusercontent.com/44803127/104330413-3dc1e900-54ee-11eb-81f6-803a812ac416.png)
![pdf2](https://user-images.githubusercontent.com/44803127/104330463-487c7e00-54ee-11eb-9bb6-97019cccb650.png)
![pdf3](https://user-images.githubusercontent.com/44803127/104330471-4aded800-54ee-11eb-9aee-9dcfedccc726.png)

**Comment by espresso3389** [comment]
Mmm...
Basically, the rendering is by CoreGraphics and the plugin does nothing special.
Only the possible cause may be "scaling" on drawing on the Flutter Texture.

**Comment by espresso3389** [comment]
I've created a branch named `rendering_test`.
Could you please test the branch by replacing the existing pdf_render dependency on your pubspec.yaml?

```yaml
dependencies:
  pdf_render:
    git: https://github.com/espresso3389/flutter_pdf_render
    ref: rendering_test
```

**Comment by JeanChristopheMobizel** [comment]
I tried   

```
pdf_render:
    git:
      url: https://github.com/espresso3389/flutter_pdf_render
      ref: rendering_test
```

Is it possible to decrease the dart SDK version?

`Because measureall depends on pdf_render from git which requires SDK version >=2.12.0-0 <3.0.0, version solving failed.
`
