### ISSUE TITLE
Rendering breakage on recent Flutter

### ISSUE THREAD

**Issue by razfazz** [espresso3389/flutter_pdf_render#84]
I have a lot of flickering and rendering artifacts on Flutter Web when panning and zooming a pdf

I am on Flutter 3.0.4

**Comment by zogol** [comment]
i have the same issue. here is a small video of the issue. tested on high-end android device with chrome browser

https://user-images.githubusercontent.com/100768486/179200337-a9012e82-3c78-41a7-a037-5dfab1f45998.mp4

**Comment by razfazz** [comment]
any news on this bug? unfortunately this makes the package not work in web

**Comment by espresso3389** [comment]
#85 seems the same issue on iOS. So I changed the issue title not to contain specific platform.

**Comment by espresso3389** [comment]
I've added a proposal fix and could you please check the following branch?

```yaml
  flutter_pdf_render:
    git: https://github.com/espresso3389/flutter_pdf_render.git
    ref: rendering_breakage_fix_for_84
```
    
```
